type: ACTION
action-type: CHANGECONTROL_CUSTOM
language: PYTHON_3
name: Force Reload
description: Forces a device reload, and uses the devices's CVP streaming status to verify that it succeeded to reconnect and stream to CVP
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to reload
    required: true
    hidden: false
  - name: monitorTimeout
    description: Maximum time (in seconds) to monitor device for it to come back up post-reload
    required: true
    hidden: false
    default: "1200"
