type: PACKAGE
version: 1.1.1
name: shut-bgp-peers Action package
description: Action packages containing scripts to shut down/restore any BGP Unestablished Peers so that Exiting BGP maintenance mode will not fail post image upgrade
