type: ACTION
language: PYTHON_3
name: TAC-Bundle
description: Gather log bundle from EOS switches for TAC troubleshooting
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to run this script against
    required: true
    hidden: false
  - name: SRNumber
    description: The TAC case number (if not specified '1337' will be used by default).
    required: false
    hidden: false