type: ACTION
action-type: CHANGECONTROL_CUSTOM
language: PYTHON_3
name: Lightweight Enter Maintenance Mode
description: Script that makes a device enter bgp maintenance mode without running additional tests (such as tracking traffic volumes) to ensure the action succeeded
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to run this script against
    required: true
    hidden: false
