type: ACTION
action-type: CHANGECONTROL_CUSTOM
language: PYTHON_3
name: Connectivity Monitor
description: Monitor changes in Connectivity Monitor metrics post Change Control to detect changes versus historical values using a CUSUM statistical approach
file: script.py
static-params: []
dynamic-params:
  - name: Monitor Timeout
    description: The maximum time duration (in seconds) to monitor device connectivity statistics
    required: true
    hidden: false
    default: "300"
  - name: DeviceID
    description: The device to run the connectivity monitor action on
    required: true
    hidden: false
  - name: Host
    description: The host of the connectivity monitor probe
    required: true
    hidden: false
  - name: VRF
    description: The virtual routing and forwarding of the connectivity monitor probe
    required: true
    hidden: false
    default: "default"
  - name: Source Interface
    description: The source interface of the connectivity monitor probe
    required: true
    hidden: false
    default: "default"
  - name: Statistic
    description: The connectivity monitor statistic to monitor. The options are 'latency', 'http_response', 'jitter', or 'packet_loss'
    required: true
    hidden: false
    default: "latency"
  - name: Critical Level
    description: The level of change detection sensitivity. A higher critical level is less susceptible to failure
    required: true
    hidden: false
    default: "3"
  - name: Anomaly Score Threshold
    description: The value to compare CUSUM values against. When CUSUM values exceed this value threshold, an anomaly is detected. A higher threshold value is less susceptible to failure
    required: true
    hidden: false
    default: "100"
  - name: Historical Data Gathering Duration
    description: The time duration (in seconds) to retrieve historical data for the chosen metric
    required: true
    hidden: false
    default: "3600"
