type: ACTION
action-type: CHANGECONTROL_CUSTOM
language: PYTHON_3
name: Ping Host Addresses on VLAN
description: Pings all host addresses on specified VLAN subnets to ensure their connectivity
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device on which the VLAN(s) reside
    required: true
    hidden: false
  - name: VLAN IDs
    description: Enter the VLAN IDs whose subnet you wish to ping all host addresses on (Multiple VLAN IDs should be separated by commas)
    required: true
    hidden: false
    default: ""
