type: ACTION
language: PYTHON_3
name: Ping Host Addresses on VLAN
description: Forces a device reload, and uses the devices's CVP streaming status to verify that it succeeded to reconnect and stream to CVP
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to reload
    required: true
    hidden: false
  - name: VLAN IDs
    description: Enter the VLAN IDs whose subnet you wish to ping all host addresses on (Multiple VLAN IDs should be separated by commas)
    required: true
    hidden: false
    default: "" 
