type: ACTION
action-type: CHANGECONTROL_CUSTOM
language: PYTHON_3
name: Save Running Config
description: Script that saves a running config. Nothing more, nothing less
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to run this script against
    required: true
    hidden: false
