type: ACTION
language: PYTHON_3
name: Lightweight Exit BGP Maintenance Mode
description: Script that makes a device exit from BGP maintenance mode without running additional tests (such as tracking traffic volumes) to ensure the action succeeded
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to run this script against
    required: true
    hidden: false
