type: ACTION
action-type: CHANGECONTROL_CUSTOM
language: PYTHON_3
name: Revert Reload Delay Timers
description: Used to reset reload delay timers to the values they were at the start of the change control for MLAG switches.  This is the final step in completing an SSU for a switch in MLAG.
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to run this script against
    required: true
    hidden: false
