type: ACTION
action-type: CHANGECONTROL_CUSTOM
language: PYTHON_3
name: Set Reload Delay Timers to 0
description: Used when performing SSU on a switch in an MLAG pair to set the reload delay timers to 0 prior to performing the SSU.
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to run this script against
    required: true
    hidden: false
